name: skill_swap
description: A platform for exchanging skills and learning from others
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  record: ^5.0.4
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  path: ^1.8.3
  # Spezifische Firebase Versionen, die zusammen funktionieren
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true